# Music Generator with LSTM

## About

Music resamples language as a temporal sequence of articulated sounds. They say something, often something human.

Although, there are crucial differences between language and music. We can still describe it as a sequence of symbols in the simplest form of understanding. Translating something complex into something simpler, but usable by computational models.

Thus, the objective of this project is to establish a communication between the human, that understands music in the most intense way that the brain can interpret through information, and the machine.

We'll create a model that can generate music based on the input information, i.e., generate a sequence of sounds which are related in some way with the sounds passed as input.

We'll use Natural Language Processing (NLP) methods, observing the music as it were a language, abstracting it. Doing this, the machine can recognize and process similar data.

On the first step, we'll use text generation techniques, using Recurrent Neural Networks (RNNs) and Long-Short Term Memories (LSTMs). With the effectiveness of the training, even if it's reasonable, we'll perform the same implementation using specific methods such as Attention.



## Imports

In [130]:
# Basic libraries
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch.nn.functional as F

# Preprocessing data libraries
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

# Model libraries
import torch
import torch.nn as nn
import torch.optim as optim

# Data visualization
# from torch.utils.tensorboard import SummaryWriter
from tqdm.notebook import tqdm #for loading bars

# Utils
import music21
import pickle

In [3]:
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")

In [159]:
from encoder import *
from decoder import *

## Dataset

### Load data

In [8]:
data_path = '../data/'
out_encoded_path = '../encoded/'
out_decoded_path = '../decoded/'
file = 'All_I_Have_to_Do_Is_Dream'
in_file = data_path + file
out_encoded = out_encoded_path + file
out_decoded = out_decoded_path + file

N_FRAMES = 36
N_NOTES = 88
MIDI_OFFSET = 20

In [9]:
# be sure that the dirs exist
if not os.path.isdir(data_path):
    os.mkdir(data_path)
if not os.path.isdir(out_decoded_path):
    os.mkdir(out_decoded_path)
if not os.path.isdir(out_encoded_path):
    os.mkdir(out_encoded_path)

In [10]:
# get encoded data and save encoded file
encoded_song = encode_data(in_file,
                           N_FRAMES,
                           N_NOTES,
                           MIDI_OFFSET, 
                           save_as=out_encoded
                           )

Encoding file All_i_have_to_do_is_dream
Encoding Voice
Encoding Piano
Encoding Sampler
Encoding Electric guitar
Encoding Stringinstrument
Encoding Voice_
Took 12.139155626296997


### Data visualization

Each song is represented by a Pandas DataFrame where each column represents some song status. 

In [23]:
encoded_song

inst_code ks   bpm   ts    G#0     A0    B-0     B0     C1    C#1  ...  \
inst                                                                      ...   
Voice         52  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice         52  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice         52  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice         52  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice         52  C  90.0  4/4  False  False  False  False  False  False  ...   
...          ... ..   ...  ...    ...    ...    ...    ...    ...    ...  ...   
Voice_        54  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice_        54  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice_        54  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice_        54  C  90.0  4/4  False  False  False  False  False  False  ...   
Voice_        54  C  90.0  4/4  False  False  False  False  False  False  ...   

           D7    E-7     E7     F7    F#7     G7    G#7     A7    B-7     B7  
inst                                                                          
Voice   False  False  False  False  False  False  False  False  False  False  
Voice   False  False  False  False  False  False  False  False  False  False  
Voice   False  False  False  False  False  False  False  False  False  False  
Voice   False  False  False  False  False  False  False  False  False  False  
Voice   False  False  False  False  False  False  False  False  False  False  
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
Voice_  False  False  False  False  False  False  False  False  False  False  
Voice_  False  False  False  False  False  False  False  False  False  False  
Voice_  False  False  False  False  False  False  False  False  False  False  
Voice_  False  False  False  False  False  False  False  False  False  False  
Voice_  False  False  False  False  False  False  False  False  False  False  

[7164 rows x 92 columns]

In [38]:
test_piano_df = encoded_song[encoded_song.index=='Piano']
print(f'Number of frames: {len(test_piano_df.index)}')
print(f'Number of bars: {len(test_piano_df.index)//N_FRAMES}')
test_piano_df

Number of frames: 360
Number of bars: 10


inst_code ks   bpm   ts    G#0     A0    B-0     B0     C1    C#1  ...  \
inst                                                                     ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
...         ... ..   ...  ...    ...    ...    ...    ...    ...    ...  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   
Piano         5  C  90.0  4/4  False  False  False  False  False  False  ...   

          D7    E-7     E7     F7    F#7     G7    G#7     A7    B-7     B7  
inst                                                                         
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  
Piano  False  False  False  False  False  False  False  False  False  False  

[360 rows x 92 columns]

### Preprocess data

In [110]:
def get_stackframe(encoded_song, init_idx, final_idx):
    stackframe = encoded_song.iloc[init_idx:final_idx, 4:]
    stackframe = stackframe.to_numpy()
    stackframe.astype(float)
    stackframe = stackframe + 0.0
    # print(f'Stackframe shape: {stackframe.shape}')
    return stackframe
    
    

In [111]:
get_stackframe(test_piano_df, init_idx=0, final_idx=36)

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [112]:
import os
def create_dataset(root_dir, instrument, N_FRAMES=36, N_NOTES=88):
    dataset=[]
    for filename in os.listdir(root_dir):
        if filename.endswith('pkl'):
            infile = open(root_dir + filename,'rb')
            encoded_song = pickle.load(infile)
            infile.close()
            encoded_part = encoded_song[encoded_song.index==instrument]
            for i in range(len(encoded_part.index)//N_FRAMES):
                init_idx = i*(N_FRAMES)    #  0, 36  , 36*2, 36*3, ..., 36*9
                final_idx = (i+1)*N_FRAMES # 36, 36*2, 36*3, 36*4, ..., 36*10
                stackframe = get_stackframe(encoded_part, init_idx=init_idx, final_idx=final_idx)
                dataset.append(stackframe)
    
    return dataset

In [115]:
root_dir = '../encoded/'
instrument = 'Piano'

dataset = create_dataset(root_dir, instrument)
print(f'Dataset length: {len(dataset)}')

Dataset length: 10


In [123]:
X = []
y = []
for bar in dataset:
    xa = bar[:-1]
    ya = bar[1:]
    X.append(xa)
    y.append(ya)
    
X, y

([array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         ...,
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object),
  array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         ...,
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object),
  array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         ...,
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object),
  array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
         [0.0, 0.0, 0.0, ..., 0.0, 0

In [131]:
def split_dataset(dataset):
    X = []
    y = []
    
    # create two arrays X, y with bars
    for bar in dataset:
        xa = bar[:-1]
        ya = bar[1:]
        X.append(xa)
        y.append(ya)
        
    X = np.array(X, dtype='float64')
    y = np.array(y, dtype='float64')
    X = torch.from_numpy(X)
    y = torch.from_numpy(y)
    print(f'X.shape, y.shape: {X.shape, y.shape}')
    train_ds = TensorDataset(X, y)
    return train_ds

In [139]:
train_ds = split_dataset(dataset)
train_dl = DataLoader(train_ds, batch_size=1, shuffle=False)

X.shape, y.shape: (torch.Size([10, 35, 88]), torch.Size([10, 35, 88]))


## Model

Some important definitions

In [148]:
n_frames_input = 35
n_frames_output = 35
n_bars_input = len(train_dl.dataset.tensors[0]) # number of rows of the dataloader
bar_len = 35 # how many frames it's gonna take in a timestep
num_layers = 35
frame_len = 88
hidden_size = 88
num_epochs = 3
batch_size = 1
lr = 0.003
print('Number of bars in the input dataset: {}'.format(n_bars_input))

Number of bars in the input dataset: 10


In [149]:
class RNN(nn.Module):
  def __init__(self, input_size, hidden_size, num_layers, output_size):
    super(RNN, self).__init__()
    self.hidden_size = hidden_size
    self.num_layers = num_layers

    #self.embed = nn.Embedding(input_size, hidden_size)
    self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=False)
    self.fc = nn.Linear(hidden_size, output_size)
    self.act = nn.Hardsigmoid()

  def forward(self, x, hidden, cell):

    # Passing in the input and hidden state into the model and obtaining outputs
    out, (hidden, cell) = self.lstm(x.unsqueeze(1), (hidden, cell))

    # Reshaping the outputs such that it can be fit into the fully connected layer
    out = self.fc(out.contiguous().view(-1, self.hidden_size))
    out = self.act(out)
    
    return out, (hidden, cell)

  def init_hidden(self, batch_size):
    # This method generates the first hidden state of zeros which we'll use in the forward pass
    # We'll send the tensor holding the hidden state to the device we specified earlier as well
    hidden = torch.zeros(self.num_layers, batch_size, self.hidden_size).to(device)
    cell = torch.zeros(self.num_layers, batch_size, self.hidden_size).to(device)
    return hidden, cell

In [150]:
# Instantiate the model with hyperparameters
# We'll also set the model to the device that we defined earlier (default is CPU)
model = RNN(input_size=frame_len,
                   output_size=frame_len,
                   hidden_size=hidden_size,
                   num_layers=num_layers).to(device)

## Train

In [151]:
# converts one frame into torch tensor
def multi_hot_tensor(frame):
  tensor = torch.from_numpy(frame)
  return tensor

In [152]:
# retrieve data from dataloader
def get_sample(dataloader):

  input = torch.zeros(n_bars_input, bar_len, frame_len)
  target = torch.zeros(n_bars_input, bar_len, frame_len)

  for sample, (xb, yb) in enumerate(dataloader): # gets the samples
    input[sample] = xb
    target[sample] = yb
  
  return input, target

In [153]:
def train(model, optimizer, loss_fn, dataloader, batch_size=1, num_epochs=3):

  print("\nStarting training...")

  for epoch in range(1, num_epochs + 1):
    training_loss = 0.0

    print('> EPOCH #', epoch)

    input, target = get_sample(dataloader)
    input = input.to(device)
    target = target.to(device)

    for bar in tqdm(range(n_bars_input)):
      # Initialize hidden and cells
      hidden, cell = model.init_hidden(batch_size)

      # Generate predictions
      output, (hidden, cell) = model(input[bar,:], hidden, cell)

      # Compute the loss and backpropag         
      loss_step = loss_fn(output, target[bar, :])
      loss_step.backward() # Does backpropagation and calculates gradients
      optimizer.step() # Updates the weights accordingly
      optimizer.zero_grad() # Clears existing gradients from previous frame
      
      training_loss += loss_step.item()
    
    training_loss /= len(train_dl.dataset)
      
    if epoch%1 == 0:
      print('Epoch: {}/{}.............'.format(epoch, num_epochs), end=' ')
      print("Loss: {:.4f}".format(training_loss))

In [155]:
optimizer = optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.BCELoss()
train(model, optimizer, loss_fn, train_dl, num_epochs=50)


Starting training...
> EPOCH # 1


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 1/50............. Loss: 0.3751
> EPOCH # 2


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 2/50............. Loss: 0.3715
> EPOCH # 3


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 3/50............. Loss: 0.3717
> EPOCH # 4


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 4/50............. Loss: 0.3708
> EPOCH # 5


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 5/50............. Loss: 0.3713
> EPOCH # 6


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 6/50............. Loss: 0.3661
> EPOCH # 7


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 7/50............. Loss: 0.3442
> EPOCH # 8


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 8/50............. Loss: 0.3206
> EPOCH # 9


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 9/50............. Loss: 0.2926
> EPOCH # 10


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 10/50............. Loss: 0.2919
> EPOCH # 11


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 11/50............. Loss: 0.2910
> EPOCH # 12


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 12/50............. Loss: 0.2932
> EPOCH # 13


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 13/50............. Loss: 0.2900
> EPOCH # 14


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 14/50............. Loss: 0.2895
> EPOCH # 15


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 15/50............. Loss: 0.2900
> EPOCH # 16


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 16/50............. Loss: 0.2895
> EPOCH # 17


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 17/50............. Loss: 0.2862
> EPOCH # 18


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 18/50............. Loss: 0.2552
> EPOCH # 19


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 19/50............. Loss: 0.2005
> EPOCH # 20


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 20/50............. Loss: 0.1704
> EPOCH # 21


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 21/50............. Loss: 0.1472
> EPOCH # 22


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 22/50............. Loss: 0.1437
> EPOCH # 23


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 23/50............. Loss: 0.1343
> EPOCH # 24


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 24/50............. Loss: 0.1343
> EPOCH # 25


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 25/50............. Loss: 0.1283
> EPOCH # 26


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 26/50............. Loss: 0.1290
> EPOCH # 27


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 27/50............. Loss: 0.1128
> EPOCH # 28


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 28/50............. Loss: 0.1192
> EPOCH # 29


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 29/50............. Loss: 0.1076
> EPOCH # 30


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 30/50............. Loss: 0.1069
> EPOCH # 31


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 31/50............. Loss: 0.1190
> EPOCH # 32


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 32/50............. Loss: 0.1060
> EPOCH # 33


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 33/50............. Loss: 0.1060
> EPOCH # 34


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 34/50............. Loss: 0.1054
> EPOCH # 35


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 35/50............. Loss: 0.1057
> EPOCH # 36


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 36/50............. Loss: 0.1056
> EPOCH # 37


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 37/50............. Loss: 0.1054
> EPOCH # 38


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 38/50............. Loss: 0.1055
> EPOCH # 39


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 39/50............. Loss: 0.1054
> EPOCH # 40


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 40/50............. Loss: 0.1054
> EPOCH # 41


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 41/50............. Loss: 0.1054
> EPOCH # 42


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 42/50............. Loss: 0.1054
> EPOCH # 43


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 43/50............. Loss: 0.1054
> EPOCH # 44


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 44/50............. Loss: 0.1054
> EPOCH # 45


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 45/50............. Loss: 0.1053
> EPOCH # 46


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 46/50............. Loss: 0.1053
> EPOCH # 47


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 47/50............. Loss: 0.1053
> EPOCH # 48


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 48/50............. Loss: 0.1053
> EPOCH # 49


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 49/50............. Loss: 0.1053
> EPOCH # 50


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch: 50/50............. Loss: 0.1053


## Test

In [160]:
def generate(model, initial_bar, predict_len=36, batch_size=1, temperature=0.85):
  output = []
  hidden, cell = model.init_hidden(batch_size)
  initial_bar = initial_bar.to(device)
  for _ in range(predict_len):
    out, (hidden, cell) = model(initial_bar, hidden, cell)
    output.append(out)
  
  return output

In [161]:
initial_bar = train_dl.dataset.tensors[0][5]
initial_bar = initial_bar.to(torch.float)
print(f'Input: ')
torch.set_printoptions(threshold=10_000)
print(initial_bar)

output = generate(model, initial_bar, predict_len=1)
print(f'Output: ')
print(output)

Input: 
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 1., 0., 1

In [163]:
data_out = decode_data(output, N_FRAMES, N_NOTES, save_as=out_decoded)

TypeError: 'builtin_function_or_method' object is not iterable